version: '3.8'

services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mail-lime
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
